# Generated by Django 3.1.4 on 2021-01-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'banji',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20)),
                ('t_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('t_age', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, db_column='c_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher1', to='app1.course')),
                ('grade', models.ForeignKey(blank=True, db_column='g_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher2', to='app1.grade')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_sex', models.CharField(max_length=10, null=True)),
                ('s_age', models.IntegerField(null=True)),
                ('banji', models.OneToOneField(blank=True, db_column='b_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app1.banji')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_value', models.FloatField(null=True)),
                ('course', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, related_name='score1', to='app1.course')),
                ('student', models.ForeignKey(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, related_name='score2', to='app1.student')),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('master', models.ForeignKey(blank=True, db_column='m_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='app1.teacher')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='g_master',
            field=models.ForeignKey(blank=True, db_column='gm_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade2', to='app1.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(blank=True, db_column='s_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade1', to='app1.school'),
        ),
        migrations.AddField(
            model_name='banji',
            name='b_master',
            field=models.ForeignKey(blank=True, db_column='t_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banji2', to='app1.teacher'),
        ),
        migrations.AddField(
            model_name='banji',
            name='grade',
            field=models.ForeignKey(blank=True, db_column='g_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banji1', to='app1.grade'),
        ),
    ]
