# Generated by Django 3.1.4 on 2021-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='s_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='s_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
