# Generated by Django 3.1.4 on 2021-01-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210126_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(blank=True, db_column='g_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='app1.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='banji',
            field=models.OneToOneField(blank=True, db_column='b_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='app1.banji'),
        ),
    ]
